name: Periodic Check
on:
  schedule:
    - cron:  '31 1,12 * * *'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Latest V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout VTL
      uses: actions/checkout@v2
      with:
        path: vtl
    - name: Build V
      run: |
        make
        sudo ./v symlink
    - name: V doctor
      run: v doctor
    - name: Install VTL dependencies
      run: |
        sudo apt-get install --quiet -y --no-install-recommends gfortran liblapacke-dev libopenblas-dev
        v install vsl
    - name: Symlink vtl to .vmodules
      run: ln -s $(realpath vtl) ~/.vmodules/vtl
    - name: Execute Tests using Pure V Backend with Vlib Math
      run: cd vtl; ./bin/test
    - name: Execute Tests using Pure V Backend with Pure V Math
      run: cd vtl; ./bin/test --use-vmath
    - name: Execute Tests using Open BLAS Backend
      run: cd vtl; ./bin/test --use-cblas
    - name: Execute Tests using Open BLAS Backend and Pure V Math
      run: cd vtl; ./bin/test --use-vmath --use-cblas
