name: Periodic

on:
  schedule:
    - cron:  '31 1,12 * * *'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up V version latest
      uses: nocturlab/setup-vlang-action@v1
      with:
        v-version: latest
      id: v
    - name: run tests
      run: make test
